# Colonizer example verify ID file for KVM/QEMU (test lab) deployment
#
- hosts: all
  become: yes
  vars:
    ignore_disk_names: ["vda", "sda", "sdf", "sr0", "sr1", "dm-0", "dm-1", "dm-2", "dm-3", "dm-4"]
  tasks:
    - assert:
        that: 
          - ansible_processor_vcpus == 12
            #- ansible_product_version == 'pc-i440fx-2.9'
          - ansible_memtotal_mb >= 250
          - ansible_architecture == 'x86_64'
          - ansible_system_vendor == 'Cisco Systems Inc'
          - ansible_distribution == 'RedHat'
          - ansible_distribution_major_version == '7'
          - (ansible_devices|length) >= 3

#    - name: check if disk sizes and naming is as expected
#      with_items: "{{ (ansible_devices.keys() | difference(ignore_disk_names)) }}"
#      assert:
#        that:
#          - ansible_devices[item]['size'] >= '200.00 GB'
#          - item.startswith('sd')

    # Depends on presence of package python-dnf
    - name: Install dependency for ansible selinux management
      package:
        name: libselinux-python.x86_64
        state: present

    - selinux:
        policy: targeted
        state: enforcing
